
name: Static Analysis
on:
  workflow_call:

permissions:
  contents: read
  security-events: write  # 👈 REQUIRED for uploading SARIF    

jobs:
  static_analysis:
    name: 🧠 Static Analysis (Semgrep + Bandit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          pip install bandit semgrep bandit-sarif-formatter

# ─────────────── BANDIT SCAN ───────────────

      - name: Run Bandit
        run: |
          bandit -r app -f json -o bandit_results.json || true
          bandit -r app -f sarif -o bandit_results.sarif || true

# ─────────────── SEMGREP SCAN ───────────────

      - name: Run Semgrep manually to file
        run: |
          semgrep scan --config p/ci --json > semgrep_results.json || true
          semgrep scan --config p/ci --sarif > semgrep_results.sarif || true

# ─────────────── UPLOAD RESULTS ───────────────

      - name: 📤 Upload Bandit SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit_results.sarif
          category: bandit-static-scan

      - name: 📤 Upload Semgrep SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep_results.sarif
          category: semgrep-static-scan

      - name: Upload Static Analysis Reports
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-reports
          path: |
            bandit_results.json
            semgrep_results.json